/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ModulesRouteImport } from './routes/modules'
import { Route as InstallRouteImport } from './routes/install'
import { Route as DonutsmpGuideRouteImport } from './routes/donutsmp-guide'
import { Route as DonutsmpFlyBypassRouteImport } from './routes/donutsmp-fly-bypass'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostsIndexRouteImport } from './routes/posts.index'
import { Route as PostsSlugRouteImport } from './routes/posts.$slug'

const ModulesRoute = ModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const DonutsmpGuideRoute = DonutsmpGuideRouteImport.update({
  id: '/donutsmp-guide',
  path: '/donutsmp-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const DonutsmpFlyBypassRoute = DonutsmpFlyBypassRouteImport.update({
  id: '/donutsmp-fly-bypass',
  path: '/donutsmp-fly-bypass',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsSlugRoute = PostsSlugRouteImport.update({
  id: '/posts/$slug',
  path: '/posts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/donutsmp-fly-bypass': typeof DonutsmpFlyBypassRoute
  '/donutsmp-guide': typeof DonutsmpGuideRoute
  '/install': typeof InstallRoute
  '/modules': typeof ModulesRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/posts/': typeof PostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/donutsmp-fly-bypass': typeof DonutsmpFlyBypassRoute
  '/donutsmp-guide': typeof DonutsmpGuideRoute
  '/install': typeof InstallRoute
  '/modules': typeof ModulesRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/posts': typeof PostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/donutsmp-fly-bypass': typeof DonutsmpFlyBypassRoute
  '/donutsmp-guide': typeof DonutsmpGuideRoute
  '/install': typeof InstallRoute
  '/modules': typeof ModulesRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/posts/': typeof PostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/changelog'
    | '/donutsmp-fly-bypass'
    | '/donutsmp-guide'
    | '/install'
    | '/modules'
    | '/posts/$slug'
    | '/posts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/changelog'
    | '/donutsmp-fly-bypass'
    | '/donutsmp-guide'
    | '/install'
    | '/modules'
    | '/posts/$slug'
    | '/posts'
  id:
    | '__root__'
    | '/'
    | '/changelog'
    | '/donutsmp-fly-bypass'
    | '/donutsmp-guide'
    | '/install'
    | '/modules'
    | '/posts/$slug'
    | '/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangelogRoute: typeof ChangelogRoute
  DonutsmpFlyBypassRoute: typeof DonutsmpFlyBypassRoute
  DonutsmpGuideRoute: typeof DonutsmpGuideRoute
  InstallRoute: typeof InstallRoute
  ModulesRoute: typeof ModulesRoute
  PostsSlugRoute: typeof PostsSlugRoute
  PostsIndexRoute: typeof PostsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/modules': {
      id: '/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof ModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donutsmp-guide': {
      id: '/donutsmp-guide'
      path: '/donutsmp-guide'
      fullPath: '/donutsmp-guide'
      preLoaderRoute: typeof DonutsmpGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donutsmp-fly-bypass': {
      id: '/donutsmp-fly-bypass'
      path: '/donutsmp-fly-bypass'
      fullPath: '/donutsmp-fly-bypass'
      preLoaderRoute: typeof DonutsmpFlyBypassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$slug': {
      id: '/posts/$slug'
      path: '/posts/$slug'
      fullPath: '/posts/$slug'
      preLoaderRoute: typeof PostsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangelogRoute: ChangelogRoute,
  DonutsmpFlyBypassRoute: DonutsmpFlyBypassRoute,
  DonutsmpGuideRoute: DonutsmpGuideRoute,
  InstallRoute: InstallRoute,
  ModulesRoute: ModulesRoute,
  PostsSlugRoute: PostsSlugRoute,
  PostsIndexRoute: PostsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
